namespace ISDK.Filuet.OnlineOrdering.CorePlugin.Plugin_Data
{
    public static class DefaultSettingsData
    {
        public static string ChangedSettings => @"
{
  'addresssettings.companyenabled': 'False',
  'addresssettings.faxenabled': 'False',
  'addresssettings.stateprovinceenabled': 'False',
  'addresssettings.streetaddress2enabled': 'False',
  'blogsettings.allownotregistereduserstoleavecomments': 'False',
  'catalogsettings.allowviewunpublishedproductpage': 'False',
  'catalogsettings.cacheproductprices': 'True',
  'catalogsettings.compareproductsenabled': 'False',
  'catalogsettings.defaultcategorypagesize': '18',
  'catalogsettings.defaultcategorypagesizeoptions': '18, 9, 6, 3',
  'catalogsettings.defaultmanufacturerpagesize': '18',
  'catalogsettings.defaultmanufacturerpagesizeoptions': '18, 9, 6, 3',
  'catalogsettings.displaydiscontinuedmessageforunpublishedproducts': 'False',
  'catalogsettings.emailafriendenabled': 'False',
  'catalogsettings.ignorestorelimitations': 'False',
  'catalogsettings.newproductsenabled': 'False',
  'catalogsettings.productsortingenumdisabled': '15,0',
  'catalogsettings.productsortingenumdisplayorder': '15, 15;0, 0',
  'catalogsettings.searchpagepagesizeoptions': '18, 9, 6, 3',
  'catalogsettings.searchpageproductsperpage': '18',
  'catalogsettings.showcategoryproductnumber': 'True',
  'catalogsettings.showcategoryproductnumberincludingsubcategories': 'True',
  'catalogsettings.showfreeshippingnotification': 'False',
  'catalogsettings.showproductimagesinsearchautocomplete': 'True',
  'catalogsettings.showproductreviewstabonaccountpage': 'False',
  'catalogsettings.showproductsfromsubcategories': 'True',
  'catalogsettings.showsharebutton': 'False',
  'commonsettings.sitemapincludemanufacturers': 'False',
  'commonsettings.usestoredprocedureforloadingcategories': 'True',
  'commonsettings.usesystememailforcontactusform': 'False',
  'currencysettings.activeexchangerateprovidersystemname': 'CurrencyExchange.ECB',
  'currencysettings.primaryexchangeratecurrencyid': '6',
  'currencysettings.primarystorecurrencyid': '6',
  'customersettings.companyenabled': 'False',
  'customersettings.countryenabled': 'True',
  'customersettings.failedpasswordallowedattempts': '6',
  'customersettings.passwordminlength': '8',
  'customersettings.usernamesenabled': 'True',  
  'datetimesettings.defaultstoretimezoneid': 'UTC',
  'displaydefaultmenuitemsettings.displayblogmenuitem': 'False',
  'displaydefaultmenuitemsettings.displaycontactusmenuitem': 'False',
  'displaydefaultmenuitemsettings.displaycustomerinfomenuitem': 'False',
  'displaydefaultmenuitemsettings.displayforumsmenuitem': 'False',
  'displaydefaultmenuitemsettings.displayhomepagemenuitem': 'False',
  'displaydefaultmenuitemsettings.displaynewproductsmenuitem': 'False',
  'emailaccountsettings.defaultemailaccountid': '2',
  'googleanalyticssettings.googleid': 'UA-124572337-1',
  'googleanalyticssettings.widgetzone': 'body_end_html_tag_before',
  'instantsearchsettings.searchoption': '1',
  'instantsearchsettings.showsku': 'True',
  'localizationsettings.loadalllocalerecordsonstartup': 'False',
  'localizationsettings.loadalllocalizedpropertiesonstartup': 'False',
  'localizationsettings.useimagesforlanguageselection': 'True',
  'mediasettings.productdetailspicturesize': '380',  
  'motionthemesettings.preset': '7bc143',
  'motionthemesettings.productimageproportion': '100.0000',
  'motionthemesettings.removecopyright': 'True',
  'motionthemesettings.removedesignedby': 'True',
  'nivoslidersettings.link1': 'https://blt.myfiluet.com/',
  'nivoslidersettings.link2': 'https://blt.myfiluet.com/',
  'nopajaxcartsettings.enablerelatedproductsinpopup': 'True',
  'nopajaxfilterssettings.enableattributesfilter': 'False',
  'ordersettings.anonymouscheckoutallowed': 'False',
  'ordersettings.disablebillingaddresscheckoutstep': 'True',
  'ordersettings.minimumorderplacementinterval': '10',
  'ordersettings.minordersubtotalamount': '0.0000',
  'ordersettings.minordertotalamount': '0.0000',
  'ordersettings.onepagecheckoutenabled': 'True',
  'ordersettings.termsofserviceonshoppingcartpage': 'False',
  'paymentsettings.activepaymentmethodsystemnames': 'ISDK.Filuet.OnlineOrdering.PayeezyPayments,ISDK.Filuet.OnlineOrdering.SEBPayments,ISDK.Filuet.OnlineOrdering.SwedbankPayments',
  'producteditorsettings.crosssellsproducts': 'True',
  'producteditorsettings.disablewishlistbutton': 'True',
  'producteditorsettings.maximumcartquantity': 'True',
  'quickviewsettings.accordionpanelsheightstyle': 'auto',
  'quickviewsettings.showcompareproductsbutton': 'False',
  'quickviewsettings.showfullproductdescription': 'True',
  'quickviewsettings.showproductspecification': 'False',
  'rewardpointssettings.enabled': 'False',
  'securitysettings.encryptionkey': '1137167068647048',
  'securitysettings.forcesslforallpages': 'True',
  'seosettings.defaulttitle': 'Uzbekistan Online Ordering | Herbalife',
  'seosettings.pagetitleseparator': '|',
  'shoppingcartsettings.emailwishlistenabled': 'False',
  'shoppingcartsettings.maximumwishlistitems': '0',
  'shoppingcartsettings.moveitemsfromwishlisttocart': 'False',
  'shoppingcartsettings.showgiftcardbox': 'False',
  'shoppingcartsettings.showproductimagesonwishlist': 'False',
  'storeinformationsettings.defaultstoretheme': 'Motion',
  'storeinformationsettings.displayeucookielawwarning': 'True',
  'storeinformationsettings.facebooklink': 'http://facebook.com/herbalifersm',
  'storeinformationsettings.googlepluslink': '',
  'storeinformationsettings.logopictureid': '155',
  'storeinformationsettings.twitterlink': '',
  'storeinformationsettings.youtubelink': 'http://youtube.com/herbaliferus',
  'tabsettings.enableproductcontactustab': 'False',
  'tabsettings.enableproductreviewstab': 'False',
  'tabsettings.enableproductspecificationstab': 'False',
  'widgetsettings.activewidgetsystemnames': 'SevenSpikes.Nop.Plugins.AjaxCart,SevenSpikes.Nop.Plugins.AjaxFilters,SevenSpikes.Nop.Plugins.AnywhereSliders,SevenSpikes.Nop.Plugins.CloudZoom,SevenSpikes.Nop.Plugins.InstantSearch,SevenSpikes.Nop.Plugins.JCarousel,SevenSpikes.Nop.Plugins.MegaMenu,SevenSpikes.Nop.Plugins.ProductRibbons,SevenSpikes.Nop.Plugins.NopQuickTabs,SevenSpikes.Nop.Plugins.QuickView,SevenSpikes.Theme.Motion,Widgets.GoogleAnalytics'
}
";
    }
}
