//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.1c.ru/SSL/Exchange", ConfigurationName="ServiceReference1.HLOrdersPortType")]
    public interface HLOrdersPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.1c.ru/SSL/Exchange#HLOrders:CheckPartner", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CheckPartnerResponse> CheckPartnerAsync(ServiceReference1.CheckPartnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.1c.ru/SSL/Exchange#HLOrders:GetOrderStatuses", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetOrderStatusesResponse> GetOrderStatusesAsync(ServiceReference1.GetOrderStatusesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.1c.ru/SSL/Exchange#HLOrders:GetStocks", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetStocksResponse> GetStocksAsync(ServiceReference1.GetStocksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.1c.ru/SSL/Exchange#HLOrders:SendOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.SendOrderResponse> SendOrderAsync(ServiceReference1.SendOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.1c.ru/SSL/Exchange#HLOrders:CreateDover", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CreateDoverResponse> CreateDoverAsync(ServiceReference1.CreateDoverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.1c.ru/SSL/Exchange#HLOrders:GetPromoDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetPromoDetailsResponse> GetPromoDetailsAsync(ServiceReference1.GetPromoDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.1c.ru/SSL/Exchange#HLOrders:SendPromoAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.SendPromoAddressResponse> SendPromoAddressAsync(ServiceReference1.SendPromoAddressRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPartnerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPartner", Namespace="http://www.1c.ru/SSL/Exchange", Order=0)]
        public ServiceReference1.CheckPartnerRequestBody Body;
        
        public CheckPartnerRequest()
        {
        }
        
        public CheckPartnerRequest(ServiceReference1.CheckPartnerRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.1c.ru/SSL/Exchange")]
    public partial class CheckPartnerRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDPartner;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string INNPartner;
        
        public CheckPartnerRequestBody()
        {
        }
        
        public CheckPartnerRequestBody(string IDPartner, string INNPartner)
        {
            this.IDPartner = IDPartner;
            this.INNPartner = INNPartner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPartnerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPartnerResponse", Namespace="http://www.1c.ru/SSL/Exchange", Order=0)]
        public ServiceReference1.CheckPartnerResponseBody Body;
        
        public CheckPartnerResponse()
        {
        }
        
        public CheckPartnerResponse(ServiceReference1.CheckPartnerResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.1c.ru/SSL/Exchange")]
    public partial class CheckPartnerResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string result;
        
        public CheckPartnerResponseBody()
        {
        }
        
        public CheckPartnerResponseBody(string @return, string result)
        {
            this.@return = @return;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderStatusesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderStatuses", Namespace="http://www.1c.ru/SSL/Exchange", Order=0)]
        public ServiceReference1.GetOrderStatusesRequestBody Body;
        
        public GetOrderStatusesRequest()
        {
        }
        
        public GetOrderStatusesRequest(ServiceReference1.GetOrderStatusesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.1c.ru/SSL/Exchange")]
    public partial class GetOrderStatusesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OrdersList;
        
        public GetOrderStatusesRequestBody()
        {
        }
        
        public GetOrderStatusesRequestBody(string OrdersList)
        {
            this.OrdersList = OrdersList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderStatusesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderStatusesResponse", Namespace="http://www.1c.ru/SSL/Exchange", Order=0)]
        public ServiceReference1.GetOrderStatusesResponseBody Body;
        
        public GetOrderStatusesResponse()
        {
        }
        
        public GetOrderStatusesResponse(ServiceReference1.GetOrderStatusesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.1c.ru/SSL/Exchange")]
    public partial class GetOrderStatusesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string result;
        
        public GetOrderStatusesResponseBody()
        {
        }
        
        public GetOrderStatusesResponseBody(string @return, string result)
        {
            this.@return = @return;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStocksRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStocks", Namespace="http://www.1c.ru/SSL/Exchange", Order=0)]
        public ServiceReference1.GetStocksRequestBody Body;
        
        public GetStocksRequest()
        {
        }
        
        public GetStocksRequest(ServiceReference1.GetStocksRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStocksRequestBody
    {
        
        public GetStocksRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStocksResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStocksResponse", Namespace="http://www.1c.ru/SSL/Exchange", Order=0)]
        public ServiceReference1.GetStocksResponseBody Body;
        
        public GetStocksResponse()
        {
        }
        
        public GetStocksResponse(ServiceReference1.GetStocksResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.1c.ru/SSL/Exchange")]
    public partial class GetStocksResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string result;
        
        public GetStocksResponseBody()
        {
        }
        
        public GetStocksResponseBody(string @return, string result)
        {
            this.@return = @return;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOrder", Namespace="http://www.1c.ru/SSL/Exchange", Order=0)]
        public ServiceReference1.SendOrderRequestBody Body;
        
        public SendOrderRequest()
        {
        }
        
        public SendOrderRequest(ServiceReference1.SendOrderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.1c.ru/SSL/Exchange")]
    public partial class SendOrderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OrderText;
        
        public SendOrderRequestBody()
        {
        }
        
        public SendOrderRequestBody(string OrderText)
        {
            this.OrderText = OrderText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOrderResponse", Namespace="http://www.1c.ru/SSL/Exchange", Order=0)]
        public ServiceReference1.SendOrderResponseBody Body;
        
        public SendOrderResponse()
        {
        }
        
        public SendOrderResponse(ServiceReference1.SendOrderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.1c.ru/SSL/Exchange")]
    public partial class SendOrderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string result;
        
        public SendOrderResponseBody()
        {
        }
        
        public SendOrderResponseBody(string @return, string result)
        {
            this.@return = @return;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDoverRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDover", Namespace="http://www.1c.ru/SSL/Exchange", Order=0)]
        public ServiceReference1.CreateDoverRequestBody Body;
        
        public CreateDoverRequest()
        {
        }
        
        public CreateDoverRequest(ServiceReference1.CreateDoverRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.1c.ru/SSL/Exchange")]
    public partial class CreateDoverRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string timestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PartnerFIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PartnerDocNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PartnerDocOrg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PartnerDocDate;
        
        public CreateDoverRequestBody()
        {
        }
        
        public CreateDoverRequestBody(string timestamp, string OrderID, string PartnerFIO, string PartnerDocNum, string PartnerDocOrg, string PartnerDocDate)
        {
            this.timestamp = timestamp;
            this.OrderID = OrderID;
            this.PartnerFIO = PartnerFIO;
            this.PartnerDocNum = PartnerDocNum;
            this.PartnerDocOrg = PartnerDocOrg;
            this.PartnerDocDate = PartnerDocDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDoverResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDoverResponse", Namespace="http://www.1c.ru/SSL/Exchange", Order=0)]
        public ServiceReference1.CreateDoverResponseBody Body;
        
        public CreateDoverResponse()
        {
        }
        
        public CreateDoverResponse(ServiceReference1.CreateDoverResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.1c.ru/SSL/Exchange")]
    public partial class CreateDoverResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ResultFile;
        
        public CreateDoverResponseBody()
        {
        }
        
        public CreateDoverResponseBody(string @return, string ResultFile)
        {
            this.@return = @return;
            this.ResultFile = ResultFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPromoDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPromoDetails", Namespace="http://www.1c.ru/SSL/Exchange", Order=0)]
        public ServiceReference1.GetPromoDetailsRequestBody Body;
        
        public GetPromoDetailsRequest()
        {
        }
        
        public GetPromoDetailsRequest(ServiceReference1.GetPromoDetailsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.1c.ru/SSL/Exchange")]
    public partial class GetPromoDetailsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDPartner;
        
        public GetPromoDetailsRequestBody()
        {
        }
        
        public GetPromoDetailsRequestBody(string IDPartner)
        {
            this.IDPartner = IDPartner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPromoDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPromoDetailsResponse", Namespace="http://www.1c.ru/SSL/Exchange", Order=0)]
        public ServiceReference1.GetPromoDetailsResponseBody Body;
        
        public GetPromoDetailsResponse()
        {
        }
        
        public GetPromoDetailsResponse(ServiceReference1.GetPromoDetailsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.1c.ru/SSL/Exchange")]
    public partial class GetPromoDetailsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string result;
        
        public GetPromoDetailsResponseBody()
        {
        }
        
        public GetPromoDetailsResponseBody(string @return, string result)
        {
            this.@return = @return;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPromoAddressRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPromoAddress", Namespace="http://www.1c.ru/SSL/Exchange", Order=0)]
        public ServiceReference1.SendPromoAddressRequestBody Body;
        
        public SendPromoAddressRequest()
        {
        }
        
        public SendPromoAddressRequest(ServiceReference1.SendPromoAddressRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.1c.ru/SSL/Exchange")]
    public partial class SendPromoAddressRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NomID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address;
        
        public SendPromoAddressRequestBody()
        {
        }
        
        public SendPromoAddressRequestBody(string NomID, string Address)
        {
            this.NomID = NomID;
            this.Address = Address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPromoAddressResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPromoAddressResponse", Namespace="http://www.1c.ru/SSL/Exchange", Order=0)]
        public ServiceReference1.SendPromoAddressResponseBody Body;
        
        public SendPromoAddressResponse()
        {
        }
        
        public SendPromoAddressResponse(ServiceReference1.SendPromoAddressResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.1c.ru/SSL/Exchange")]
    public partial class SendPromoAddressResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string result;
        
        public SendPromoAddressResponseBody()
        {
        }
        
        public SendPromoAddressResponseBody(string @return, string result)
        {
            this.@return = @return;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface HLOrdersPortTypeChannel : ServiceReference1.HLOrdersPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class HLOrdersPortTypeClient : System.ServiceModel.ClientBase<ServiceReference1.HLOrdersPortType>, ServiceReference1.HLOrdersPortType
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HLOrdersPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(HLOrdersPortTypeClient.GetBindingForEndpoint(endpointConfiguration), HLOrdersPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HLOrdersPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HLOrdersPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HLOrdersPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HLOrdersPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HLOrdersPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CheckPartnerResponse> ServiceReference1.HLOrdersPortType.CheckPartnerAsync(ServiceReference1.CheckPartnerRequest request)
        {
            return base.Channel.CheckPartnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CheckPartnerResponse> CheckPartnerAsync(string IDPartner, string INNPartner)
        {
            ServiceReference1.CheckPartnerRequest inValue = new ServiceReference1.CheckPartnerRequest();
            inValue.Body = new ServiceReference1.CheckPartnerRequestBody();
            inValue.Body.IDPartner = IDPartner;
            inValue.Body.INNPartner = INNPartner;
            return ((ServiceReference1.HLOrdersPortType)(this)).CheckPartnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetOrderStatusesResponse> ServiceReference1.HLOrdersPortType.GetOrderStatusesAsync(ServiceReference1.GetOrderStatusesRequest request)
        {
            return base.Channel.GetOrderStatusesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetOrderStatusesResponse> GetOrderStatusesAsync(string OrdersList)
        {
            ServiceReference1.GetOrderStatusesRequest inValue = new ServiceReference1.GetOrderStatusesRequest();
            inValue.Body = new ServiceReference1.GetOrderStatusesRequestBody();
            inValue.Body.OrdersList = OrdersList;
            return ((ServiceReference1.HLOrdersPortType)(this)).GetOrderStatusesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetStocksResponse> ServiceReference1.HLOrdersPortType.GetStocksAsync(ServiceReference1.GetStocksRequest request)
        {
            return base.Channel.GetStocksAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetStocksResponse> GetStocksAsync()
        {
            ServiceReference1.GetStocksRequest inValue = new ServiceReference1.GetStocksRequest();
            inValue.Body = new ServiceReference1.GetStocksRequestBody();
            return ((ServiceReference1.HLOrdersPortType)(this)).GetStocksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.SendOrderResponse> ServiceReference1.HLOrdersPortType.SendOrderAsync(ServiceReference1.SendOrderRequest request)
        {
            return base.Channel.SendOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SendOrderResponse> SendOrderAsync(string OrderText)
        {
            ServiceReference1.SendOrderRequest inValue = new ServiceReference1.SendOrderRequest();
            inValue.Body = new ServiceReference1.SendOrderRequestBody();
            inValue.Body.OrderText = OrderText;
            return ((ServiceReference1.HLOrdersPortType)(this)).SendOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CreateDoverResponse> ServiceReference1.HLOrdersPortType.CreateDoverAsync(ServiceReference1.CreateDoverRequest request)
        {
            return base.Channel.CreateDoverAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreateDoverResponse> CreateDoverAsync(string timestamp, string OrderID, string PartnerFIO, string PartnerDocNum, string PartnerDocOrg, string PartnerDocDate)
        {
            ServiceReference1.CreateDoverRequest inValue = new ServiceReference1.CreateDoverRequest();
            inValue.Body = new ServiceReference1.CreateDoverRequestBody();
            inValue.Body.timestamp = timestamp;
            inValue.Body.OrderID = OrderID;
            inValue.Body.PartnerFIO = PartnerFIO;
            inValue.Body.PartnerDocNum = PartnerDocNum;
            inValue.Body.PartnerDocOrg = PartnerDocOrg;
            inValue.Body.PartnerDocDate = PartnerDocDate;
            return ((ServiceReference1.HLOrdersPortType)(this)).CreateDoverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetPromoDetailsResponse> ServiceReference1.HLOrdersPortType.GetPromoDetailsAsync(ServiceReference1.GetPromoDetailsRequest request)
        {
            return base.Channel.GetPromoDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetPromoDetailsResponse> GetPromoDetailsAsync(string IDPartner)
        {
            ServiceReference1.GetPromoDetailsRequest inValue = new ServiceReference1.GetPromoDetailsRequest();
            inValue.Body = new ServiceReference1.GetPromoDetailsRequestBody();
            inValue.Body.IDPartner = IDPartner;
            return ((ServiceReference1.HLOrdersPortType)(this)).GetPromoDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.SendPromoAddressResponse> ServiceReference1.HLOrdersPortType.SendPromoAddressAsync(ServiceReference1.SendPromoAddressRequest request)
        {
            return base.Channel.SendPromoAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SendPromoAddressResponse> SendPromoAddressAsync(string NomID, string Address)
        {
            ServiceReference1.SendPromoAddressRequest inValue = new ServiceReference1.SendPromoAddressRequest();
            inValue.Body = new ServiceReference1.SendPromoAddressRequestBody();
            inValue.Body.NomID = NomID;
            inValue.Body.Address = Address;
            return ((ServiceReference1.HLOrdersPortType)(this)).SendPromoAddressAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HLOrdersSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HLOrdersSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HLOrdersSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://185.74.6.251/FUZ_T_HRBL/ru_RU/ws/HLOrders");
            }
            if ((endpointConfiguration == EndpointConfiguration.HLOrdersSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://185.74.6.251/FUZ_T_HRBL/ru_RU/ws/HLOrders");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HLOrdersSoap,
            
            HLOrdersSoap12,
        }
    }
}
