//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ProxyServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizationResult", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class AuthorizationResult : object
    {
        
        private string AccessTokenField;
        
        private ProxyServiceReference.AuthorizationStatusEnum AuthorizationStatusField;
        
        private ProxyServiceReference.UserInformation UserInformationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken
        {
            get
            {
                return this.AccessTokenField;
            }
            set
            {
                this.AccessTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyServiceReference.AuthorizationStatusEnum AuthorizationStatus
        {
            get
            {
                return this.AuthorizationStatusField;
            }
            set
            {
                this.AuthorizationStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyServiceReference.UserInformation UserInformation
        {
            get
            {
                return this.UserInformationField;
            }
            set
            {
                this.UserInformationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInformation", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class UserInformation : object
    {
        
        private System.DateTime APFDueDateField;
        
        private ProxyServiceReference.DistributorAddress[] AddressesField;
        
        private string AdvisoryFlagField;
        
        private bool CashOnlyField;
        
        private string CountryofProcessingField;
        
        private ProxyServiceReference.DistributorDiscount DiscountField;
        
        private ProxyServiceReference.DistributorStatus DistributorStatusField;
        
        private string DistributorSubTypeField;
        
        private ProxyServiceReference.DistributorType DistributorTypeField;
        
        private string EmailField;
        
        private string FRSSFFlagField;
        
        private string FirstNameField;
        
        private string IdField;
        
        private bool IsDebtorField;
        
        private bool IsDualMonthAllowedField;
        
        private string ItalyDSTypeField;
        
        private string LastNameField;
        
        private string MailingCountryField;
        
        private string PhoneField;
        
        private double PpvField;
        
        private double PvField;
        
        private string ResidenceCountryField;
        
        private double TvField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime APFDueDate
        {
            get
            {
                return this.APFDueDateField;
            }
            set
            {
                this.APFDueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyServiceReference.DistributorAddress[] Addresses
        {
            get
            {
                return this.AddressesField;
            }
            set
            {
                this.AddressesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdvisoryFlag
        {
            get
            {
                return this.AdvisoryFlagField;
            }
            set
            {
                this.AdvisoryFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CashOnly
        {
            get
            {
                return this.CashOnlyField;
            }
            set
            {
                this.CashOnlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryofProcessing
        {
            get
            {
                return this.CountryofProcessingField;
            }
            set
            {
                this.CountryofProcessingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyServiceReference.DistributorDiscount Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyServiceReference.DistributorStatus DistributorStatus
        {
            get
            {
                return this.DistributorStatusField;
            }
            set
            {
                this.DistributorStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistributorSubType
        {
            get
            {
                return this.DistributorSubTypeField;
            }
            set
            {
                this.DistributorSubTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyServiceReference.DistributorType DistributorType
        {
            get
            {
                return this.DistributorTypeField;
            }
            set
            {
                this.DistributorTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FRSSFFlag
        {
            get
            {
                return this.FRSSFFlagField;
            }
            set
            {
                this.FRSSFFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDebtor
        {
            get
            {
                return this.IsDebtorField;
            }
            set
            {
                this.IsDebtorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDualMonthAllowed
        {
            get
            {
                return this.IsDualMonthAllowedField;
            }
            set
            {
                this.IsDualMonthAllowedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItalyDSType
        {
            get
            {
                return this.ItalyDSTypeField;
            }
            set
            {
                this.ItalyDSTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailingCountry
        {
            get
            {
                return this.MailingCountryField;
            }
            set
            {
                this.MailingCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Ppv
        {
            get
            {
                return this.PpvField;
            }
            set
            {
                this.PpvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Pv
        {
            get
            {
                return this.PvField;
            }
            set
            {
                this.PvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResidenceCountry
        {
            get
            {
                return this.ResidenceCountryField;
            }
            set
            {
                this.ResidenceCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Tv
        {
            get
            {
                return this.TvField;
            }
            set
            {
                this.TvField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizationStatusEnum", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public enum AuthorizationStatusEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidId = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPin = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotCompleteAdvisory = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ForeignPurchaseRestriction = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CantBuy = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorDiscount", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class DistributorDiscount : object
    {
        
        private double MaxField;
        
        private double MinField;
        
        private double ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Max
        {
            get
            {
                return this.MaxField;
            }
            set
            {
                this.MaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Min
        {
            get
            {
                return this.MinField;
            }
            set
            {
                this.MinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorAddress", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class DistributorAddress : object
    {
        
        private string AddressField;
        
        private string AddressTypeField;
        
        private string CityField;
        
        private string CountryField;
        
        private string StateField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressType
        {
            get
            {
                return this.AddressTypeField;
            }
            set
            {
                this.AddressTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorStatus", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public enum DistributorStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Complete = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Temporary = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Terminated = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Incomplete = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorType", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public enum DistributorType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Supervisor = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Distributor = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreferredCustomer = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CharterPreferredCustomer = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorLimits", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProxyServiceReference.DistributorLimitsWithBalance))]
    public partial class DistributorLimits : object
    {
        
        private ProxyServiceReference.DistributorLimitEnum DistributorLimitField;
        
        private System.Nullable<double> ExceedanceAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyServiceReference.DistributorLimitEnum DistributorLimit
        {
            get
            {
                return this.DistributorLimitField;
            }
            set
            {
                this.DistributorLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ExceedanceAmount
        {
            get
            {
                return this.ExceedanceAmountField;
            }
            set
            {
                this.ExceedanceAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorLimitsWithBalance", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class DistributorLimitsWithBalance : ProxyServiceReference.DistributorLimits
    {
        
        private ProxyServiceReference.SkuItem[] ExceedItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyServiceReference.SkuItem[] ExceedItems
        {
            get
            {
                return this.ExceedItemsField;
            }
            set
            {
                this.ExceedItemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorLimitEnum", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public enum DistributorLimitEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotExceed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FirstOrderLimitExceed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MonthlyLimitExceed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exceed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoLimits = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VolumeAllowanceExceed = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkuItem", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class SkuItem : object
    {
        
        private string NameField;
        
        private string WarehouseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warehouse
        {
            get
            {
                return this.WarehouseField;
            }
            set
            {
                this.WarehouseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItem", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProxyServiceReference.ShoppingCartLine))]
    public partial class OrderItem : object
    {
        
        private int CountField;
        
        private ProxyServiceReference.SkuItem SkuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyServiceReference.SkuItem Sku
        {
            get
            {
                return this.SkuField;
            }
            set
            {
                this.SkuField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCartLine", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class ShoppingCartLine : ProxyServiceReference.OrderItem
    {
        
        private System.Nullable<decimal> EarnbaseField;
        
        private System.Nullable<decimal> LineAmountField;
        
        private System.Nullable<decimal> LineTotalAmountField;
        
        private System.Nullable<decimal> TotalDiscountedPriceField;
        
        private System.Nullable<decimal> TotalEarnbaseField;
        
        private System.Nullable<decimal> TotalRetailPriceField;
        
        private System.Nullable<decimal> UnitPriceField;
        
        private System.Nullable<decimal> UnitVolumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Earnbase
        {
            get
            {
                return this.EarnbaseField;
            }
            set
            {
                this.EarnbaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LineAmount
        {
            get
            {
                return this.LineAmountField;
            }
            set
            {
                this.LineAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LineTotalAmount
        {
            get
            {
                return this.LineTotalAmountField;
            }
            set
            {
                this.LineTotalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalDiscountedPrice
        {
            get
            {
                return this.TotalDiscountedPriceField;
            }
            set
            {
                this.TotalDiscountedPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalEarnbase
        {
            get
            {
                return this.TotalEarnbaseField;
            }
            set
            {
                this.TotalEarnbaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalRetailPrice
        {
            get
            {
                return this.TotalRetailPriceField;
            }
            set
            {
                this.TotalRetailPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> UnitPrice
        {
            get
            {
                return this.UnitPriceField;
            }
            set
            {
                this.UnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> UnitVolume
        {
            get
            {
                return this.UnitVolumeField;
            }
            set
            {
                this.UnitVolumeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorFopLimits", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class DistributorFopLimits : object
    {
        
        private decimal AvailableAiLimitField;
        
        private decimal AvailableFopLimitField;
        
        private decimal AvailablePcLimitField;
        
        private System.DateTime FopFirstOrderDateField;
        
        private double FopLimitField;
        
        private int FopThresholdPeriodField;
        
        private bool InFopPeriodField;
        
        private double PcLimitField;
        
        private decimal ThresholdAiLimitField;
        
        private decimal ThresholdFopLimitField;
        
        private decimal ThresholdPcLimitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableAiLimit
        {
            get
            {
                return this.AvailableAiLimitField;
            }
            set
            {
                this.AvailableAiLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableFopLimit
        {
            get
            {
                return this.AvailableFopLimitField;
            }
            set
            {
                this.AvailableFopLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailablePcLimit
        {
            get
            {
                return this.AvailablePcLimitField;
            }
            set
            {
                this.AvailablePcLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FopFirstOrderDate
        {
            get
            {
                return this.FopFirstOrderDateField;
            }
            set
            {
                this.FopFirstOrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FopLimit
        {
            get
            {
                return this.FopLimitField;
            }
            set
            {
                this.FopLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FopThresholdPeriod
        {
            get
            {
                return this.FopThresholdPeriodField;
            }
            set
            {
                this.FopThresholdPeriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InFopPeriod
        {
            get
            {
                return this.InFopPeriodField;
            }
            set
            {
                this.InFopPeriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PcLimit
        {
            get
            {
                return this.PcLimitField;
            }
            set
            {
                this.PcLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ThresholdAiLimit
        {
            get
            {
                return this.ThresholdAiLimitField;
            }
            set
            {
                this.ThresholdAiLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ThresholdFopLimit
        {
            get
            {
                return this.ThresholdFopLimitField;
            }
            set
            {
                this.ThresholdFopLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ThresholdPcLimit
        {
            get
            {
                return this.ThresholdPcLimitField;
            }
            set
            {
                this.ThresholdPcLimitField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalCashLimit", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class PersonalCashLimit : object
    {
        
        private decimal AvailableAmountField;
        
        private decimal LimitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableAmount
        {
            get
            {
                return this.AvailableAmountField;
            }
            set
            {
                this.AvailableAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Limit
        {
            get
            {
                return this.LimitField;
            }
            set
            {
                this.LimitField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCartTotal", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class ShoppingCartTotal : object
    {
        
        private decimal AmountBaseField;
        
        private double CurrentOrderVolumePointsField;
        
        private double DiscountField;
        
        private double DiscountPercentField;
        
        private decimal DiscountedBasePriceField;
        
        private string[] ErrorsField;
        
        private decimal FreightChargeField;
        
        private string OracleResponseField;
        
        private System.Nullable<System.DateTime> OrderDateField;
        
        private int OrderMonthField;
        
        private string OrderNumberField;
        
        private int OrderYearField;
        
        private System.Nullable<System.DateTime> PriceDateField;
        
        private decimal RewardAmountBaseField;
        
        private ProxyServiceReference.ShoppingCartLine[] ShoppingCartLinesField;
        
        private decimal TotalAmountField;
        
        private decimal TotalDueField;
        
        private decimal TotalLogisticChargesField;
        
        private decimal TotalOtherChargesField;
        
        private decimal TotalPHChargesField;
        
        private decimal TotalProductRetailField;
        
        private decimal TotalRetailAmountField;
        
        private decimal TotalTaxAmountField;
        
        private double VolumePointsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AmountBase
        {
            get
            {
                return this.AmountBaseField;
            }
            set
            {
                this.AmountBaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CurrentOrderVolumePoints
        {
            get
            {
                return this.CurrentOrderVolumePointsField;
            }
            set
            {
                this.CurrentOrderVolumePointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DiscountPercent
        {
            get
            {
                return this.DiscountPercentField;
            }
            set
            {
                this.DiscountPercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiscountedBasePrice
        {
            get
            {
                return this.DiscountedBasePriceField;
            }
            set
            {
                this.DiscountedBasePriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FreightCharge
        {
            get
            {
                return this.FreightChargeField;
            }
            set
            {
                this.FreightChargeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OracleResponse
        {
            get
            {
                return this.OracleResponseField;
            }
            set
            {
                this.OracleResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderDate
        {
            get
            {
                return this.OrderDateField;
            }
            set
            {
                this.OrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderMonth
        {
            get
            {
                return this.OrderMonthField;
            }
            set
            {
                this.OrderMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderYear
        {
            get
            {
                return this.OrderYearField;
            }
            set
            {
                this.OrderYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PriceDate
        {
            get
            {
                return this.PriceDateField;
            }
            set
            {
                this.PriceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RewardAmountBase
        {
            get
            {
                return this.RewardAmountBaseField;
            }
            set
            {
                this.RewardAmountBaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyServiceReference.ShoppingCartLine[] ShoppingCartLines
        {
            get
            {
                return this.ShoppingCartLinesField;
            }
            set
            {
                this.ShoppingCartLinesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmount
        {
            get
            {
                return this.TotalAmountField;
            }
            set
            {
                this.TotalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDue
        {
            get
            {
                return this.TotalDueField;
            }
            set
            {
                this.TotalDueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalLogisticCharges
        {
            get
            {
                return this.TotalLogisticChargesField;
            }
            set
            {
                this.TotalLogisticChargesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalOtherCharges
        {
            get
            {
                return this.TotalOtherChargesField;
            }
            set
            {
                this.TotalOtherChargesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPHCharges
        {
            get
            {
                return this.TotalPHChargesField;
            }
            set
            {
                this.TotalPHChargesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalProductRetail
        {
            get
            {
                return this.TotalProductRetailField;
            }
            set
            {
                this.TotalProductRetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalRetailAmount
        {
            get
            {
                return this.TotalRetailAmountField;
            }
            set
            {
                this.TotalRetailAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalTaxAmount
        {
            get
            {
                return this.TotalTaxAmountField;
            }
            set
            {
                this.TotalTaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VolumePoints
        {
            get
            {
                return this.VolumePointsField;
            }
            set
            {
                this.VolumePointsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPayment", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class OrderPayment : object
    {
        
        private System.Nullable<System.DateTime> AppliedDateField;
        
        private string ApprovalNumberField;
        
        private System.Nullable<System.DateTime> CardExpiryDateField;
        
        private string CardHolderNameField;
        
        private string CardNumberField;
        
        private string CardTypeField;
        
        private string CurrencyCodeField;
        
        private string PaycodeField;
        
        private System.Nullable<decimal> PaymentAmountField;
        
        private System.Nullable<System.DateTime> PaymentDateField;
        
        private string PaymentMethodIdField;
        
        private string PaymentMethodNameField;
        
        private System.Nullable<decimal> PaymentReceivedField;
        
        private string PaymentTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AppliedDate
        {
            get
            {
                return this.AppliedDateField;
            }
            set
            {
                this.AppliedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApprovalNumber
        {
            get
            {
                return this.ApprovalNumberField;
            }
            set
            {
                this.ApprovalNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CardExpiryDate
        {
            get
            {
                return this.CardExpiryDateField;
            }
            set
            {
                this.CardExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardHolderName
        {
            get
            {
                return this.CardHolderNameField;
            }
            set
            {
                this.CardHolderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardType
        {
            get
            {
                return this.CardTypeField;
            }
            set
            {
                this.CardTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode
        {
            get
            {
                return this.CurrencyCodeField;
            }
            set
            {
                this.CurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paycode
        {
            get
            {
                return this.PaycodeField;
            }
            set
            {
                this.PaycodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PaymentAmount
        {
            get
            {
                return this.PaymentAmountField;
            }
            set
            {
                this.PaymentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PaymentDate
        {
            get
            {
                return this.PaymentDateField;
            }
            set
            {
                this.PaymentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethodId
        {
            get
            {
                return this.PaymentMethodIdField;
            }
            set
            {
                this.PaymentMethodIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethodName
        {
            get
            {
                return this.PaymentMethodNameField;
            }
            set
            {
                this.PaymentMethodNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PaymentReceived
        {
            get
            {
                return this.PaymentReceivedField;
            }
            set
            {
                this.PaymentReceivedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentType
        {
            get
            {
                return this.PaymentTypeField;
            }
            set
            {
                this.PaymentTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPaymentStatus", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Commin.Data")]
    public enum OrderPaymentStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        [Display(Description = "PAID")]
        Paid = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        [Display(Description = "UNDERPAID")]
        Underpaid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        [Display(Description = "OVERPAID")]
        Overpaid = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitOrderResult", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class SubmitOrderResult : object
    {
        
        private string[] ErrorsField;
        
        private bool IsSuccessField;
        
        private string OrderNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess
        {
            get
            {
                return this.IsSuccessField;
            }
            set
            {
                this.IsSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HPSPaymentResult", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class HPSPaymentResult : object
    {
        
        private string ApprovalNumField;
        
        private int ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string TransactionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApprovalNum
        {
            get
            {
                return this.ApprovalNumField;
            }
            set
            {
                this.ApprovalNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockBalance", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class StockBalance : object
    {
        
        private ProxyServiceReference.StockBalanceItem[] StockBalancesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyServiceReference.StockBalanceItem[] StockBalances
        {
            get
            {
                return this.StockBalancesField;
            }
            set
            {
                this.StockBalancesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockBalanceItem", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public partial class StockBalanceItem : object
    {
        
        private bool IsAvailableField;
        
        private bool IsBlockedField;
        
        private bool IsValidField;
        
        private ProxyServiceReference.SkuItem SkuField;
        
        private ProxyServiceReference.StockBalanceItemAvailabilityEnum StockBalanceItemAvailabilityField;
        
        private int StockQtyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable
        {
            get
            {
                return this.IsAvailableField;
            }
            set
            {
                this.IsAvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBlocked
        {
            get
            {
                return this.IsBlockedField;
            }
            set
            {
                this.IsBlockedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid
        {
            get
            {
                return this.IsValidField;
            }
            set
            {
                this.IsValidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyServiceReference.SkuItem Sku
        {
            get
            {
                return this.SkuField;
            }
            set
            {
                this.SkuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyServiceReference.StockBalanceItemAvailabilityEnum StockBalanceItemAvailability
        {
            get
            {
                return this.StockBalanceItemAvailabilityField;
            }
            set
            {
                this.StockBalanceItemAvailabilityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockQty
        {
            get
            {
                return this.StockQtyField;
            }
            set
            {
                this.StockQtyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockBalanceItemAvailabilityEnum", Namespace="http://schemas.datacontract.org/2004/07/HBL.Baltic.OnlineOrdering.Common.Data")]
    public enum StockBalanceItemAvailabilityEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Available = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidSku = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnavailableOnStock = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyServiceReference.IFusionServiceProxy")]
    public interface IFusionServiceProxy
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/AuthorizeUser", ReplyAction="http://tempuri.org/IAuthorizationService/AuthorizeUserResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.AuthorizationResult> AuthorizeUserAsync(string userId, string pin, string countryCode, string shipToCountryCode, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/ValidateDistributorLimits", ReplyAction="http://tempuri.org/IShoppingCartService/ValidateDistributorLimitsResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.DistributorLimits> ValidateDistributorLimitsAsync(string distributorId, string countryCode, double cartVolumePoints, string orderMonth, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/ValidateDistributorLimitsWithBalance", ReplyAction="http://tempuri.org/IShoppingCartService/ValidateDistributorLimitsWithBalanceRespo" +
            "nse")]
        System.Threading.Tasks.Task<ProxyServiceReference.DistributorLimitsWithBalance> ValidateDistributorLimitsWithBalanceAsync(string distributorId, string countryCode, double cartVolumePoints, string orderMonth, ProxyServiceReference.OrderItem[] orderItems, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/GetDistributorLimits", ReplyAction="http://tempuri.org/IShoppingCartService/GetDistributorLimitsResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.DistributorFopLimits> GetDistributorLimitsAsync(string distributorId, string countryCode, string orderMonth, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/GetDistributorDiscount", ReplyAction="http://tempuri.org/IShoppingCartService/GetDistributorDiscountResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.DistributorDiscount> GetDistributorDiscountAsync(string distributorId, System.DateTime orderMonth, string shipToCountry, string environment, string serviceConsumer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/GetDistributorCashAmountLimit", ReplyAction="http://tempuri.org/IShoppingCartService/GetDistributorCashAmountLimitResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.PersonalCashLimit> GetDistributorCashAmountLimitAsync(string userId, string countryCode, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/GetShoppingCartTotal", ReplyAction="http://tempuri.org/IShoppingCartService/GetShoppingCartTotalResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.ShoppingCartTotal> GetShoppingCartTotalAsync(
                    string distributorId, 
                    string processingLocation, 
                    string warehouseCode, 
                    string orderMonth, 
                    string freightCode, 
                    string countryCode, 
                    string postalCode, 
                    string address, 
                    string city, 
                    ProxyServiceReference.OrderItem[] orderItems, 
                    string orderNumber, 
                    string orderCategory, 
                    string orderType, 
                    string state, 
                    string address2, 
                    string orderSubType, 
                    string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/SubmitOrder", ReplyAction="http://tempuri.org/IShoppingCartService/SubmitOrderResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.SubmitOrderResult> SubmitOrderAsync(
                    string distributorId, 
                    string customerName, 
                    string processingLocation, 
                    string warehouseCode, 
                    string orderMonth, 
                    string freightCode, 
                    string countryCode, 
                    string postalCode, 
                    string address, 
                    string city, 
                    string phone, 
                    string timeSlot, 
                    string postamatCode, 
                    ProxyServiceReference.ShoppingCartTotal shoppingCart, 
                    ProxyServiceReference.OrderPayment payment, 
                    ProxyServiceReference.ShoppingCartLine[] orderItems, 
                    string orderTypeCode, 
                    string orderTypeId, 
                    bool invoiceWithShipment, 
                    string notes, 
                    string salesChannelCode, 
                    string clientRefNumber, 
                    string smsNumber, 
                    string orderConfirmEmail, 
                    string smsAction, 
                    string smsRole, 
                    string invShipFlag, 
                    string state, 
                    string address2, 
                    string pickupName, 
                    string shippingInstructions, 
                    string province, 
                    string orgId, 
                    string orderSubType, 
                    string orderPurpose, 
                    string environment, 
                    ProxyServiceReference.OrderPaymentStatus paymentStatus,
                    bool preservePhone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/HpsPayment", ReplyAction="http://tempuri.org/IShoppingCartService/HpsPaymentResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.HPSPaymentResult> HpsPaymentAsync(
                    string orderNumber, 
                    string distributorId, 
                    string currency, 
                    decimal amount, 
                    string cardholderName, 
                    string cardNumber, 
                    int expiryMonth, 
                    int expiryYear, 
                    string cvv, 
                    string country, 
                    string processingLocation, 
                    string cardType, 
                    string payeeId, 
                    int installments, 
                    string clientRefNum, 
                    string address, 
                    string city, 
                    string postalCode, 
                    string orderType, 
                    string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockBalanceService/GetStockBalance", ReplyAction="http://tempuri.org/IStockBalanceService/GetStockBalanceResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.StockBalance> GetStockBalanceAsync(ProxyServiceReference.OrderItem[] skuList, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFusionServiceProxy/GetData", ReplyAction="http://tempuri.org/IFusionServiceProxy/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFusionServiceProxy/GetError", ReplyAction="http://tempuri.org/IFusionServiceProxy/GetErrorResponse")]
        System.Threading.Tasks.Task<string> GetErrorAsync(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IFusionServiceProxyChannel : ProxyServiceReference.IFusionServiceProxy, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class FusionServiceProxyClient : System.ServiceModel.ClientBase<ProxyServiceReference.IFusionServiceProxy>, ProxyServiceReference.IFusionServiceProxy
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FusionServiceProxyClient() : 
                base(FusionServiceProxyClient.GetDefaultBinding(), FusionServiceProxyClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IFusionServiceProxy.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FusionServiceProxyClient(EndpointConfiguration endpointConfiguration) : 
                base(FusionServiceProxyClient.GetBindingForEndpoint(endpointConfiguration), FusionServiceProxyClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FusionServiceProxyClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FusionServiceProxyClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FusionServiceProxyClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FusionServiceProxyClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FusionServiceProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.AuthorizationResult> AuthorizeUserAsync(string userId, string pin, string countryCode, string shipToCountryCode, string environment)
        {
            return base.Channel.AuthorizeUserAsync(userId, pin, countryCode, shipToCountryCode, environment);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.DistributorLimits> ValidateDistributorLimitsAsync(string distributorId, string countryCode, double cartVolumePoints, string orderMonth, string environment)
        {
            return base.Channel.ValidateDistributorLimitsAsync(distributorId, countryCode, cartVolumePoints, orderMonth, environment);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.DistributorLimitsWithBalance> ValidateDistributorLimitsWithBalanceAsync(string distributorId, string countryCode, double cartVolumePoints, string orderMonth, ProxyServiceReference.OrderItem[] orderItems, string environment)
        {
            return base.Channel.ValidateDistributorLimitsWithBalanceAsync(distributorId, countryCode, cartVolumePoints, orderMonth, orderItems, environment);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.DistributorFopLimits> GetDistributorLimitsAsync(string distributorId, string countryCode, string orderMonth, string environment)
        {
            return base.Channel.GetDistributorLimitsAsync(distributorId, countryCode, orderMonth, environment);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.DistributorDiscount> GetDistributorDiscountAsync(string distributorId, System.DateTime orderMonth, string shipToCountry, string environment, string serviceConsumer)
        {
            return base.Channel.GetDistributorDiscountAsync(distributorId, orderMonth, shipToCountry, environment, serviceConsumer);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.PersonalCashLimit> GetDistributorCashAmountLimitAsync(string userId, string countryCode, string environment)
        {
            return base.Channel.GetDistributorCashAmountLimitAsync(userId, countryCode, environment);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.ShoppingCartTotal> GetShoppingCartTotalAsync(
                    string distributorId, 
                    string processingLocation, 
                    string warehouseCode, 
                    string orderMonth, 
                    string freightCode, 
                    string countryCode, 
                    string postalCode, 
                    string address, 
                    string city, 
                    ProxyServiceReference.OrderItem[] orderItems, 
                    string orderNumber, 
                    string orderCategory, 
                    string orderType, 
                    string state, 
                    string address2, 
                    string orderSubType, 
                    string environment)
        {
            return base.Channel.GetShoppingCartTotalAsync(distributorId, processingLocation, warehouseCode, orderMonth, freightCode, countryCode, postalCode, address, city, orderItems, orderNumber, orderCategory, orderType, state, address2, orderSubType, environment);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.SubmitOrderResult> SubmitOrderAsync(
                    string distributorId, 
                    string customerName, 
                    string processingLocation, 
                    string warehouseCode, 
                    string orderMonth, 
                    string freightCode, 
                    string countryCode, 
                    string postalCode, 
                    string address, 
                    string city, 
                    string phone, 
                    string timeSlot, 
                    string postamatCode, 
                    ProxyServiceReference.ShoppingCartTotal shoppingCart, 
                    ProxyServiceReference.OrderPayment payment, 
                    ProxyServiceReference.ShoppingCartLine[] orderItems, 
                    string orderTypeCode, 
                    string orderTypeId, 
                    bool invoiceWithShipment, 
                    string notes, 
                    string salesChannelCode, 
                    string clientRefNumber, 
                    string smsNumber, 
                    string orderConfirmEmail, 
                    string smsAction, 
                    string smsRole, 
                    string invShipFlag, 
                    string state, 
                    string address2, 
                    string pickupName, 
                    string shippingInstructions, 
                    string province, 
                    string orgId, 
                    string orderSubType, 
                    string orderPurpose, 
                    string environment, 
                    ProxyServiceReference.OrderPaymentStatus paymentStatus,
                    bool preservePhone)
        {
            return base.Channel.SubmitOrderAsync(distributorId, customerName, processingLocation, warehouseCode, orderMonth, freightCode, countryCode, postalCode, address, city, phone, timeSlot, postamatCode, shoppingCart, payment, orderItems, orderTypeCode, orderTypeId, invoiceWithShipment, notes, salesChannelCode, clientRefNumber, smsNumber, orderConfirmEmail, smsAction, smsRole, invShipFlag, state, address2, pickupName, shippingInstructions, province, orgId, orderSubType, orderPurpose, environment, paymentStatus, preservePhone);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.HPSPaymentResult> HpsPaymentAsync(
                    string orderNumber, 
                    string distributorId, 
                    string currency, 
                    decimal amount, 
                    string cardholderName, 
                    string cardNumber, 
                    int expiryMonth, 
                    int expiryYear, 
                    string cvv, 
                    string country, 
                    string processingLocation, 
                    string cardType, 
                    string payeeId, 
                    int installments, 
                    string clientRefNum, 
                    string address, 
                    string city, 
                    string postalCode, 
                    string orderType, 
                    string environment)
        {
            return base.Channel.HpsPaymentAsync(orderNumber, distributorId, currency, amount, cardholderName, cardNumber, expiryMonth, expiryYear, cvv, country, processingLocation, cardType, payeeId, installments, clientRefNum, address, city, postalCode, orderType, environment);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.StockBalance> GetStockBalanceAsync(ProxyServiceReference.OrderItem[] skuList, string environment)
        {
            return base.Channel.GetStockBalanceAsync(skuList, environment);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Threading.Tasks.Task<string> GetErrorAsync(string value)
        {
            return base.Channel.GetErrorAsync(value);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFusionServiceProxy))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFusionServiceProxy))
            {
                return new System.ServiceModel.EndpointAddress("https://10.86.9.89:8057/ProxyService.svc/FusionServiceProxy");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FusionServiceProxyClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IFusionServiceProxy);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FusionServiceProxyClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IFusionServiceProxy);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IFusionServiceProxy,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyServiceReference.IAuthorizationService")]
    public interface IAuthorizationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/AuthorizeUser", ReplyAction="http://tempuri.org/IAuthorizationService/AuthorizeUserResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.AuthorizationResult> AuthorizeUserAsync(string userId, string pin, string countryCode, string shipToCountryCode, string environment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IAuthorizationServiceChannel : ProxyServiceReference.IAuthorizationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AuthorizationServiceClient : System.ServiceModel.ClientBase<ProxyServiceReference.IAuthorizationService>, ProxyServiceReference.IAuthorizationService
    {
        
        public AuthorizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.AuthorizationResult> AuthorizeUserAsync(string userId, string pin, string countryCode, string shipToCountryCode, string environment)
        {
            return base.Channel.AuthorizeUserAsync(userId, pin, countryCode, shipToCountryCode, environment);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyServiceReference.IShoppingCartService")]
    public interface IShoppingCartService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/ValidateDistributorLimits", ReplyAction="http://tempuri.org/IShoppingCartService/ValidateDistributorLimitsResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.DistributorLimits> ValidateDistributorLimitsAsync(string distributorId, string countryCode, double cartVolumePoints, string orderMonth, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/ValidateDistributorLimitsWithBalance", ReplyAction="http://tempuri.org/IShoppingCartService/ValidateDistributorLimitsWithBalanceRespo" +
            "nse")]
        System.Threading.Tasks.Task<ProxyServiceReference.DistributorLimitsWithBalance> ValidateDistributorLimitsWithBalanceAsync(string distributorId, string countryCode, double cartVolumePoints, string orderMonth, ProxyServiceReference.OrderItem[] orderItems, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/GetDistributorLimits", ReplyAction="http://tempuri.org/IShoppingCartService/GetDistributorLimitsResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.DistributorFopLimits> GetDistributorLimitsAsync(string distributorId, string countryCode, string orderMonth, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/GetDistributorDiscount", ReplyAction="http://tempuri.org/IShoppingCartService/GetDistributorDiscountResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.DistributorDiscount> GetDistributorDiscountAsync(string distributorId, System.DateTime orderMonth, string shipToCountry, string environment, string serviceConsumer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/GetDistributorCashAmountLimit", ReplyAction="http://tempuri.org/IShoppingCartService/GetDistributorCashAmountLimitResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.PersonalCashLimit> GetDistributorCashAmountLimitAsync(string userId, string countryCode, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/GetShoppingCartTotal", ReplyAction="http://tempuri.org/IShoppingCartService/GetShoppingCartTotalResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.ShoppingCartTotal> GetShoppingCartTotalAsync(
                    string distributorId, 
                    string processingLocation, 
                    string warehouseCode, 
                    string orderMonth, 
                    string freightCode, 
                    string countryCode, 
                    string postalCode, 
                    string address, 
                    string city, 
                    ProxyServiceReference.OrderItem[] orderItems, 
                    string orderNumber, 
                    string orderCategory, 
                    string orderType, 
                    string state, 
                    string address2, 
                    string orderSubType, 
                    string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/SubmitOrder", ReplyAction="http://tempuri.org/IShoppingCartService/SubmitOrderResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.SubmitOrderResult> SubmitOrderAsync(
                    string distributorId, 
                    string customerName, 
                    string processingLocation, 
                    string warehouseCode, 
                    string orderMonth, 
                    string freightCode, 
                    string countryCode, 
                    string postalCode, 
                    string address, 
                    string city, 
                    string phone, 
                    string timeSlot, 
                    string postamatCode, 
                    ProxyServiceReference.ShoppingCartTotal shoppingCart, 
                    ProxyServiceReference.OrderPayment payment, 
                    ProxyServiceReference.ShoppingCartLine[] orderItems, 
                    string orderTypeCode, 
                    string orderTypeId, 
                    bool invoiceWithShipment, 
                    string notes, 
                    string salesChannelCode, 
                    string clientRefNumber, 
                    string smsNumber, 
                    string orderConfirmEmail, 
                    string smsAction, 
                    string smsRole, 
                    string invShipFlag, 
                    string state, 
                    string address2, 
                    string pickupName, 
                    string shippingInstructions, 
                    string province, 
                    string orgId, 
                    string orderSubType, 
                    string orderPurpose, 
                    string environment, 
                    ProxyServiceReference.OrderPaymentStatus paymentStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/HpsPayment", ReplyAction="http://tempuri.org/IShoppingCartService/HpsPaymentResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.HPSPaymentResult> HpsPaymentAsync(
                    string orderNumber, 
                    string distributorId, 
                    string currency, 
                    decimal amount, 
                    string cardholderName, 
                    string cardNumber, 
                    int expiryMonth, 
                    int expiryYear, 
                    string cvv, 
                    string country, 
                    string processingLocation, 
                    string cardType, 
                    string payeeId, 
                    int installments, 
                    string clientRefNum, 
                    string address, 
                    string city, 
                    string postalCode, 
                    string orderType, 
                    string environment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IShoppingCartServiceChannel : ProxyServiceReference.IShoppingCartService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ShoppingCartServiceClient : System.ServiceModel.ClientBase<ProxyServiceReference.IShoppingCartService>, ProxyServiceReference.IShoppingCartService
    {
        
        public ShoppingCartServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.DistributorLimits> ValidateDistributorLimitsAsync(string distributorId, string countryCode, double cartVolumePoints, string orderMonth, string environment)
        {
            return base.Channel.ValidateDistributorLimitsAsync(distributorId, countryCode, cartVolumePoints, orderMonth, environment);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.DistributorLimitsWithBalance> ValidateDistributorLimitsWithBalanceAsync(string distributorId, string countryCode, double cartVolumePoints, string orderMonth, ProxyServiceReference.OrderItem[] orderItems, string environment)
        {
            return base.Channel.ValidateDistributorLimitsWithBalanceAsync(distributorId, countryCode, cartVolumePoints, orderMonth, orderItems, environment);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.DistributorFopLimits> GetDistributorLimitsAsync(string distributorId, string countryCode, string orderMonth, string environment)
        {
            return base.Channel.GetDistributorLimitsAsync(distributorId, countryCode, orderMonth, environment);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.DistributorDiscount> GetDistributorDiscountAsync(string distributorId, System.DateTime orderMonth, string shipToCountry, string environment, string serviceConsumer)
        {
            return base.Channel.GetDistributorDiscountAsync(distributorId, orderMonth, shipToCountry, environment, serviceConsumer);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.PersonalCashLimit> GetDistributorCashAmountLimitAsync(string userId, string countryCode, string environment)
        {
            return base.Channel.GetDistributorCashAmountLimitAsync(userId, countryCode, environment);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.ShoppingCartTotal> GetShoppingCartTotalAsync(
                    string distributorId, 
                    string processingLocation, 
                    string warehouseCode, 
                    string orderMonth, 
                    string freightCode, 
                    string countryCode, 
                    string postalCode, 
                    string address, 
                    string city, 
                    ProxyServiceReference.OrderItem[] orderItems, 
                    string orderNumber, 
                    string orderCategory, 
                    string orderType, 
                    string state, 
                    string address2, 
                    string orderSubType, 
                    string environment)
        {
            return base.Channel.GetShoppingCartTotalAsync(distributorId, processingLocation, warehouseCode, orderMonth, freightCode, countryCode, postalCode, address, city, orderItems, orderNumber, orderCategory, orderType, state, address2, orderSubType, environment);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.SubmitOrderResult> SubmitOrderAsync(
                    string distributorId, 
                    string customerName, 
                    string processingLocation, 
                    string warehouseCode, 
                    string orderMonth, 
                    string freightCode, 
                    string countryCode, 
                    string postalCode, 
                    string address, 
                    string city, 
                    string phone, 
                    string timeSlot, 
                    string postamatCode, 
                    ProxyServiceReference.ShoppingCartTotal shoppingCart, 
                    ProxyServiceReference.OrderPayment payment, 
                    ProxyServiceReference.ShoppingCartLine[] orderItems, 
                    string orderTypeCode, 
                    string orderTypeId, 
                    bool invoiceWithShipment, 
                    string notes, 
                    string salesChannelCode, 
                    string clientRefNumber, 
                    string smsNumber, 
                    string orderConfirmEmail, 
                    string smsAction, 
                    string smsRole, 
                    string invShipFlag, 
                    string state, 
                    string address2, 
                    string pickupName, 
                    string shippingInstructions, 
                    string province, 
                    string orgId, 
                    string orderSubType, 
                    string orderPurpose, 
                    string environment, 
                    ProxyServiceReference.OrderPaymentStatus paymentStatus)
        {
            return base.Channel.SubmitOrderAsync(distributorId, customerName, processingLocation, warehouseCode, orderMonth, freightCode, countryCode, postalCode, address, city, phone, timeSlot, postamatCode, shoppingCart, payment, orderItems, orderTypeCode, orderTypeId, invoiceWithShipment, notes, salesChannelCode, clientRefNumber, smsNumber, orderConfirmEmail, smsAction, smsRole, invShipFlag, state, address2, pickupName, shippingInstructions, province, orgId, orderSubType, orderPurpose, environment, paymentStatus);
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.HPSPaymentResult> HpsPaymentAsync(
                    string orderNumber, 
                    string distributorId, 
                    string currency, 
                    decimal amount, 
                    string cardholderName, 
                    string cardNumber, 
                    int expiryMonth, 
                    int expiryYear, 
                    string cvv, 
                    string country, 
                    string processingLocation, 
                    string cardType, 
                    string payeeId, 
                    int installments, 
                    string clientRefNum, 
                    string address, 
                    string city, 
                    string postalCode, 
                    string orderType, 
                    string environment)
        {
            return base.Channel.HpsPaymentAsync(orderNumber, distributorId, currency, amount, cardholderName, cardNumber, expiryMonth, expiryYear, cvv, country, processingLocation, cardType, payeeId, installments, clientRefNum, address, city, postalCode, orderType, environment);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyServiceReference.IStockBalanceService")]
    public interface IStockBalanceService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockBalanceService/GetStockBalance", ReplyAction="http://tempuri.org/IStockBalanceService/GetStockBalanceResponse")]
        System.Threading.Tasks.Task<ProxyServiceReference.StockBalance> GetStockBalanceAsync(ProxyServiceReference.OrderItem[] skuList, string environment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IStockBalanceServiceChannel : ProxyServiceReference.IStockBalanceService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class StockBalanceServiceClient : System.ServiceModel.ClientBase<ProxyServiceReference.IStockBalanceService>, ProxyServiceReference.IStockBalanceService
    {
        
        public StockBalanceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ProxyServiceReference.StockBalance> GetStockBalanceAsync(ProxyServiceReference.OrderItem[] skuList, string environment)
        {
            return base.Channel.GetStockBalanceAsync(skuList, environment);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
